name: "GCR Docker builder"
description: "Build docker images that can be uploaded to gcr.io"
author: "Soren Mathiasen"
runs:
  using: "docker"
  image: "docker://eu.gcr.io/tradeshift-public/gcr-docker-push:v2"
branding:
  icon: "check-square"
  color: "blue"
